# -*- coding: utf-8 -*-
"""First and Last index of sorted array.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1IFHTUy67cqeXIzaVc6-3eqYs2GNvKEa3
"""

### Time Complexity: O(n)
### Space Complexity: O(1)


def First_and_Last_Position(arr,target):
  array = []

  for i in arr:
    num = int(i)
    array.append(num)

  position = []

  j = 0

  flag = False


  for i in range(len(array)):
    if array[i] == target:
      position.append(i)
      j = i+1
      flag = True
      break

  if flag == True:
    while True: 
      if array[j] == target:
        j = j+1
        pass
      else:
        j = j-1
        position.append(j)
        break

  else:
    position.append(-1)
    position.append(-1)

  return position



arr = list(input("Enter the sorted array: ").split(','))
target = int(input("Enter the target value ")) 

output = First_and_Last_Position(arr,target)

print(output)