# -*- coding: utf-8 -*-
"""Palindrome.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1iBobd7zAwWOPABNLot6gb-F5wZTHDMce
"""

word = input("Enter the word: ").lower()
string = ''

for i in word:
  if i == ',' or i == ' ':
    pass
  else: 
    string =string+i

newString = ''

for i in range(len(string)-1,-1,-1):
  newString = newString + string[i]

if string == newString:
  print("Palindrome")
else:
  print("Not a Palindrome")